# Generated by Django 3.2.7 on 2021-09-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20210919_2236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lights',
            new_name='Light',
        ),
        migrations.RenameModel(
            old_name='Lights_Group',
            new_name='Light_Group',
        ),
        migrations.RenameModel(
            old_name='Workstations',
            new_name='Workstation',
        ),
    ]
