# Generated by Django 3.2.7 on 2021-09-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_auto_20210920_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='colour',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='light_group',
            name='colour',
            field=models.CharField(max_length=6),
        ),
    ]
