# Generated by Django 3.2.7 on 2021-09-20 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_auto_20210920_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='brightness',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='light_group',
            name='brightness',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
