# Generated by Django 3.2.7 on 2021-10-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_auto_20210920_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='light',
            name='group_id',
        ),
        migrations.DeleteModel(
            name='Light_Group',
        ),
    ]
