# Generated by Django 3.2.7 on 2021-10-02 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_auto_20211002_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='hexcolour',
            field=models.CharField(default=datetime.datetime(2021, 10, 2, 10, 12, 19, 813394, tzinfo=utc), max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='light',
            name='colour',
            field=models.CharField(max_length=20),
        ),
    ]
