# Generated by Django 3.2.7 on 2021-10-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_auto_20211002_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='workstation_name',
            field=models.CharField(default='x', max_length=255),
            preserve_default=False,
        ),
    ]
