# Generated by Django 3.2.7 on 2021-10-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_auto_20211003_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='light',
            name='hexcolour',
        ),
    ]
