# Generated by Django 3.2.7 on 2021-10-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0013_auto_20211007_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=255, null=True)),
                ('wall_on', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Video_Wall_Panel',
        ),
        migrations.DeleteModel(
            name='Video_Wall_Panel_Group',
        ),
    ]
