# Generated by Django 3.2.7 on 2021-10-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0014_auto_20211008_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_wall',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
