# Generated by Django 3.2.7 on 2021-10-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0015_alter_video_wall_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='display',
            old_name='media',
            new_name='media_name',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='file_path',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='video_wall',
            old_name='media',
            new_name='media_name',
        ),
        migrations.RenameField(
            model_name='workstation',
            old_name='media',
            new_name='media_name',
        ),
        migrations.AddField(
            model_name='display',
            name='media_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='display',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video_wall',
            name='media_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video_wall',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workstation',
            name='media_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workstation',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
