# Generated by Django 3.2.7 on 2021-10-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0016_auto_20211012_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
