# Generated by Django 3.2.7 on 2021-10-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0017_alter_preset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='light',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video_wall',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
