# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestOtherTests():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testOffButton(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(1294, 1400)
    self.driver.find_element(By.ID, "recent-image").click()
    self.driver.find_element(By.CSS_SELECTOR, ".column:nth-child(3) > a img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".icon").click()
    self.driver.find_element(By.ID, "power-b").click()
    self.driver.find_element(By.CSS_SELECTOR, ".column:nth-child(3) > a img").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".icon").click()
    self.driver.find_element(By.ID, "power-b").click()
    self.driver.find_element(By.ID, "power-b").click()
    self.driver.find_element(By.CSS_SELECTOR, ".column:nth-child(3) > a img").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
  def test_workstationPageopenswithdb(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(1294, 1400)
    self.driver.find_element(By.CSS_SELECTOR, ".column:nth-child(2) > a img").click()
  
